#include <stdio.h>
#include <tamtypes.h>
#include <kernel.h>
#include <sifrpc.h>
#include <debug.h>
#include <loadfile.h>
#include <iopcontrol.h>
#include <dirent.h>
#include <malloc.h>
#include <time.h>
#include <unistd.h>
#include <fcntl.h>
#include "../libppcpatch/ppcpatch.h"

extern char patch_bin[];  //Generated by bin2s.
extern u32 size_patch_bin;


int main()
{
	int fd;
	SifInitRpc(0);
	SifLoadFileInit();
	SifIopReset("", 0);
	while (!SifIopSync()) {};
	init_scr();
	scr_setCursor(0);
	scr_printf("\n\n------------------------- PowerPc Patch Installer v0.2 -------------------------\n"
	           "\tBy Qnox32. Maintained by El_isra\n"
	           "-------------------------------------\n\n");

	if ((fd = open("rom0:DECKARD", O_RDONLY)) < 0) {
		scr_setfontcolor(0x0000ff);
		scr_printf("\tERROR: This PS2 is not a DECKARD model\n\taborting patch to avoid IOP crash\n");
		sleep(5);
		goto quit;
	} else {
		close(fd);
	}

	scr_printf("\t- patch size: 0x%x\n"
	           "\t- patch base address 0x%x\n"
	           "\t- patch branch address 0x%x\n",
	           size_patch_bin, PPCPATCH_PATCH_BASE_ADDR, PPCPATCH_PATCH_BRANCH_ADDR);

	scr_printf("\tApplying patch..");
	DeckardPatchBuffer(patch_bin, size_patch_bin);
	scr_printf(". done!\n\tFlushCache()\n");
	FlushCache(0);
	FlushCache(2);
	scr_printf("\tResetting IOP to start patch\n");
	//reset IOP to trigger branch / patch
	SifIopReset("", 0);
	while (!SifIopSync()) {};
	scr_printf("\tpatch complete!\n");

quit:
	sleep(2);

	return 0;
}



void _libcglue_timezone_update() {}
void _libcglue_init() {}
void _libcglue_deinit() {}
//DISABLE_PATCHED_FUNCTIONS();
PS2_DISABLE_AUTOSTART_PTHREAD();