title: PowerPC Monitor
description: UART controlled application for the PowerPC 440x5 CPU used on most PS2 slim models
theme: just-the-docs

url: https://israpps.github.io/PPC-Monitor/
color_scheme: dark
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-templateS


kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red