title: PowerPC Monitor
description: UART controlled application for the PowerPC 440x5 CPU used on most PS2 slim models
theme: just-the-docs

url: https://israpps.github.io/PPC-Monitor/
color_scheme: dark
#aux_links:
#  Download PowerPC Monitor: https://github.com/israpps/PPC-Monitor/releases


#nav_external_links:
#  - title: Download PowerPC Monitor
#    url: https://github.com/israpps/PPC-Monitor/releases
#  - title: PowerPC Monitor Source Code
#    url: https://github.com/israpps/PPC-Monitor/

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
      
mermaid:
  version: "10.9.0" # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
