title: PowerPC Monitor
description: UART controlled application for the PowerPC 440x5 CPU used on most PS2 slim models
theme: just-the-docs

url: https://israpps.github.io/PPC-Monitor/
color_scheme: dark
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
